update deploy75

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,21 +13,17 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Step 1: Checkout the repository
       - name: Checkout the repository
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
-      # Step 2: Verify addons directory
       - name: Verify addons directory
         run: test -d ./addons || { echo "addons directory not found"; exit 1; }
 
-      # Step 3: Verify odoo.conf file
       - name: Verify odoo.conf file
         run: test -f ./etc/odoo.conf || { echo "odoo.conf file not found"; exit 1; }
 
-      # Step 4: Copy addons and odoo.conf to docker folder
       - name: Copy addons and odoo.conf to docker folder
         run: |
           mkdir -p docker/addons
@@ -35,18 +31,15 @@ jobs:
           cp -r ./addons/* ./docker/addons/
           cp ./etc/odoo.conf ./docker/etc/odoo.conf
 
-      # Step 5: Set up Docker Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      # Step 6: Log in to Docker Hub
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Step 7: Build and Push Odoo Docker image
       - name: Build Odoo Docker image
         uses: docker/build-push-action@v2
         with:
@@ -56,14 +49,12 @@ jobs:
           cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/od:cache
           cache-to: type=inline
           
-      # Step 8: Install Docker Compose
       - name: Install Docker Compose
         run: |
           sudo apt-get update
           sudo apt-get install -y docker-compose
 
-      # Step 9: Test Odoo and PostgreSQL Integration
-            - name: Test Odoo and PostgreSQL Integration
+      - name: Test Odoo and PostgreSQL Integration
         run: |
           cat <<EOF > docker-compose.test.yml
           version: '3.8'
@@ -86,7 +77,7 @@ jobs:
               restart: always
 
             odoo16:
-              image: myodoo:16  # Use the locally built image
+              image: myodoo:16
               depends_on:
                 db:
                   condition: service_healthy
@@ -134,7 +125,10 @@ jobs:
             sleep 10
           done
 
-          curl -f http://localhost:10016 || { echo 'Odoo failed to start or connect to PostgreSQL'; exit 1; }
+          curl -f http://localhost:10016 || { echo 'Odoo failed to start or connect to PostgreSQL. Check logs for details.'; docker-compose -f docker-compose.test.yml logs; exit 1; }
 
           docker-compose -f docker-compose.test.yml logs
           docker-compose -f docker-compose.test.yml down
+
+      - name: Remove Docker Images
+        run: docker image prune -f
