update deploy64

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,24 +27,30 @@ jobs:
       - name: Verify addons directory
         run: ls -la ./addons || echo "addons directory not found"
 
-      # Step 4: Copy addons to docker folder (if necessary)
-      - name: Copy addons directory
+      # Step 4: Verify odoo.conf file exists
+      - name: Verify odoo.conf file
+        run: ls -la ./etc/odoo.conf || echo "odoo.conf file not found"
+
+      # Step 5: Copy addons and config to docker folder (if necessary)
+      - name: Copy addons and odoo.conf to docker folder
         run: |
           mkdir -p docker/addons
+          mkdir -p docker/etc
           cp -r ./addons/* ./docker/addons/
+          cp ./etc/odoo.conf ./docker/etc/odoo.conf
 
-      # Step 5: Set up Docker Buildx
+      # Step 6: Set up Docker Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      # Step 6: Log in to Docker Hub
+      # Step 7: Log in to Docker Hub
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Step 7: Build and Push Odoo Docker image
+      # Step 8: Build and Push Odoo Docker image
       - name: Build and Push Odoo Docker image
         uses: docker/build-push-action@v2
         with:
